# Generated by Django 5.1 on 2024-09-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя хаба')),
                ('link', models.TextField(verbose_name='Ссылка до главной страницы хаба')),
                ('interval', models.IntegerField(verbose_name='Интервал работы')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200, verbose_name='Заголовок публикации')),
                ('link', models.TextField(verbose_name='Ссылка до публикации')),
                ('author_name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('author_link', models.CharField(max_length=200, verbose_name='Ссылка до автора')),
                ('published_at', models.DateTimeField(verbose_name='Время публикации')),
                ('hab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.hab')),
            ],
        ),
    ]
